# Generated by Django 4.1.7 on 2023-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roll", models.PositiveIntegerField(unique=True)),
                ("dept", models.CharField(blank=True, max_length=100, null=True)),
                ("image", models.ImageField(upload_to="serializer")),
            ],
        ),
    ]
