# Generated by Django 4.1.7 on 2023-03-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("serializerapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roll", models.IntegerField()),
                ("dept", models.CharField(max_length=100)),
            ],
        ),
    ]
